/* The following code was generated by JFlex 1.3.5 on 11/24/20, 2:34 PM */

package cup.example;
import java_cup.runtime.*;
import java.io.*; 
import java.util.*; 	
import java_cup.runtime.ComplexSymbolFactory.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/24/20, 2:34 PM from the specification file
 * <tt>file:/C:/Users/mihby/eclipse-workspace/M+-/java.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\15\1\3\1\0\1\15\1\14\22\0\1\15\4\0\1\20"+
    "\1\22\1\0\1\32\1\33\1\17\1\2\1\41\1\21\1\0\1\16"+
    "\12\1\1\31\1\40\1\27\1\26\1\30\2\0\32\1\1\36\1\0"+
    "\1\37\1\0\1\1\1\0\1\11\1\46\1\53\1\45\1\7\1\10"+
    "\1\47\1\43\1\42\2\1\1\12\1\1\1\24\1\25\1\50\1\1"+
    "\1\5\1\13\1\4\1\6\1\51\1\44\2\1\1\52\1\34\1\23"+
    "\1\35\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    44,    88,    44,    44,   132,   176,   220,   264,   308, 
      352,   396,    44,   440,    44,   484,   528,   572,   616,    44, 
      660,   704,    44,    44,    44,    44,    44,    44,    44,    44, 
      748,   792,   836,   880,   924,   968,  1012,  1056,  1100,  1144, 
     1188,  1232,  1276,  1320,  1364,    44,    44,  1408,    44,    44, 
       44,    88,  1452,  1496,    88,  1540,  1584,  1628,  1672,  1716, 
     1760,  1804,  1848,  1892,    88,    88,  1936,  1980,  2024,  2068, 
       88,    88,  2112,  2156,  2200,  2244,    88,  2288,    88,  2332, 
       88,    88,    88,  2376,  2420,    88,  2464,  2508,  2552,    88, 
     2596,    88,  2640,    88,    88,    88,    88,    88,    88
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\3\1\4\1\5\1\6\1\7\1\3\1\10"+
    "\1\11\2\3\1\12\1\13\1\5\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\3\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\3\1\40\1\41\1\42\1\3\1\43"+
    "\1\44\1\3\1\45\55\0\1\3\2\0\10\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\10\3\10\0"+
    "\2\3\14\0\1\3\1\46\10\3\1\0\1\3\2\0"+
    "\3\3\1\47\4\3\10\0\2\3\14\0\12\3\1\0"+
    "\1\3\2\0\6\3\1\50\1\3\10\0\1\51\1\3"+
    "\14\0\12\3\1\0\1\3\2\0\2\3\1\52\3\3"+
    "\1\53\1\3\10\0\2\3\14\0\12\3\1\0\1\3"+
    "\2\0\10\3\10\0\2\3\14\0\1\54\11\3\3\0"+
    "\1\5\67\0\1\55\34\0\3\16\1\5\10\16\1\13"+
    "\37\16\22\0\1\56\54\0\1\57\31\0\1\3\2\0"+
    "\10\3\10\0\1\3\1\60\14\0\12\3\27\0\1\61"+
    "\52\0\1\62\53\0\1\63\26\0\1\3\2\0\4\3"+
    "\1\64\3\3\10\0\1\65\1\3\14\0\12\3\1\0"+
    "\1\3\2\0\10\3\10\0\2\3\14\0\1\3\1\66"+
    "\10\3\1\0\1\3\2\0\10\3\10\0\1\3\1\67"+
    "\14\0\12\3\1\0\1\3\2\0\3\3\1\70\4\3"+
    "\10\0\1\3\1\71\14\0\12\3\1\0\1\3\2\0"+
    "\1\3\1\72\6\3\10\0\2\3\14\0\12\3\1\0"+
    "\1\3\2\0\5\3\1\73\2\3\10\0\2\3\14\0"+
    "\12\3\1\0\1\3\2\0\3\3\1\74\4\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\3\3\1\75"+
    "\4\3\10\0\2\3\14\0\12\3\1\0\1\3\2\0"+
    "\1\76\4\3\1\77\2\3\10\0\2\3\14\0\12\3"+
    "\1\0\1\3\2\0\7\3\1\100\10\0\2\3\14\0"+
    "\12\3\1\0\1\3\2\0\10\3\10\0\2\3\14\0"+
    "\3\3\1\101\6\3\1\0\1\3\2\0\10\3\10\0"+
    "\1\102\1\3\14\0\12\3\1\0\1\3\2\0\10\3"+
    "\10\0\1\3\1\103\14\0\12\3\1\0\1\3\2\0"+
    "\10\3\10\0\2\3\14\0\10\3\1\104\1\3\17\105"+
    "\1\106\34\105\1\0\1\3\2\0\1\107\7\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\1\110\7\3"+
    "\10\0\2\3\14\0\12\3\1\0\1\3\2\0\10\3"+
    "\10\0\2\3\14\0\1\111\11\3\1\0\1\3\2\0"+
    "\10\3\10\0\2\3\14\0\5\3\1\112\4\3\1\0"+
    "\1\3\2\0\10\3\10\0\1\3\1\113\14\0\12\3"+
    "\1\0\1\3\2\0\10\3\10\0\2\3\14\0\1\114"+
    "\11\3\1\0\1\3\2\0\1\3\1\115\6\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\10\3\10\0"+
    "\2\3\14\0\1\116\11\3\1\0\1\3\2\0\10\3"+
    "\10\0\1\117\1\3\14\0\12\3\1\0\1\3\2\0"+
    "\2\3\1\120\5\3\10\0\2\3\14\0\12\3\1\0"+
    "\1\3\2\0\6\3\1\121\1\3\10\0\2\3\14\0"+
    "\3\3\1\122\6\3\1\0\1\3\2\0\3\3\1\123"+
    "\4\3\10\0\2\3\14\0\12\3\1\0\1\3\2\0"+
    "\5\3\1\124\2\3\10\0\1\3\1\125\14\0\12\3"+
    "\1\0\1\3\2\0\3\3\1\126\4\3\10\0\2\3"+
    "\14\0\12\3\17\105\1\127\34\105\16\0\1\5\1\106"+
    "\35\0\1\3\2\0\6\3\1\130\1\3\10\0\2\3"+
    "\14\0\12\3\1\0\1\3\2\0\10\3\10\0\2\3"+
    "\14\0\1\131\11\3\1\0\1\3\2\0\6\3\1\132"+
    "\1\3\10\0\2\3\14\0\12\3\1\0\1\3\2\0"+
    "\10\3\10\0\1\133\1\3\14\0\12\3\1\0\1\3"+
    "\2\0\6\3\1\134\1\3\10\0\2\3\14\0\12\3"+
    "\1\0\1\3\2\0\1\3\1\135\6\3\10\0\2\3"+
    "\14\0\12\3\1\0\1\3\2\0\1\136\7\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\1\3\1\137"+
    "\6\3\10\0\2\3\14\0\12\3\16\105\1\5\1\127"+
    "\34\105\1\0\1\3\2\0\3\3\1\140\4\3\10\0"+
    "\2\3\14\0\12\3\1\0\1\3\2\0\10\3\10\0"+
    "\1\141\1\3\14\0\12\3\1\0\1\3\2\0\1\142"+
    "\7\3\10\0\2\3\14\0\12\3\1\0\1\3\2\0"+
    "\10\3\10\0\1\143\1\3\14\0\12\3";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     1,  8,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  9,  1,  9,  0, 
     0,  1,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  9,  9,  1, 
     9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	private ComplexSymbolFactory symbolFactory;
	
	public Lexer( ComplexSymbolFactory factory, InputStream in){
	 	 this(new java.io.InputStreamReader(in));
	 	 this.symbolFactory = factory;
	}
	
	StringBuffer string = new StringBuffer();

      private Symbol symbol(int code) {
        int yylen = yylength();
    	Location left = new Location(yyline + 1, yycolumn + 1, yychar);
	    Location right = new Location(yyline + 1, yycolumn + yylen, yychar + yylen);
	    int max_code = sym.terminalNames.length;
	    String name = code < max_code ? sym.terminalNames[code] : "<UNKNOWN(" + yytext() + ")>";
	    return this.symbolFactory.newSymbol(name, code, left, right);

      }
      
      private Symbol symbol(int code, Object value) {
	    int yylen = yylength();
	    Location left = new Location(yyline + 1, yycolumn + 1, yychar);
	    Location right = new Location(yyline + 1, yycolumn + yylen, yychar + yylen);
	    int max_code = sym.terminalNames.length;
	    String name = code < max_code ? sym.terminalNames[code] : "<UNKNOWN(" + yytext() + ")>";
	    return this.symbolFactory.newSymbol(name, code, left, right, value);

      }
      
      private Symbol symbol(String name, int sym, Object val) {
      	Location left = new Location(yyline+1,yycolumn+1,yychar);
      	Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      	return symbolFactory.newSymbol(name, sym, left, right,val);
 	 } 
      


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2684];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 98: 
          {  return symbol(sym.RETURN);  }
        case 100: break;
        case 50: 
          {  return symbol(sym.ASSIGN);  }
        case 101: break;
        case 28: 
          {  return symbol(sym.SEMICOLON);  }
        case 102: break;
        case 20: 
          {  return symbol(sym.GT);  }
        case 103: break;
        case 19: 
          {  return symbol(sym.LT);  }
        case 104: break;
        case 3: 
          {  return symbol(sym.ADD);  }
        case 105: break;
        case 4: 
        case 10: 
          {  /* ignore */  }
        case 106: break;
        case 11: 
          {  return symbol(sym.DIV);  }
        case 107: break;
        case 12: 
          {  return symbol(sym.MUL);  }
        case 108: break;
        case 13: 
          {  /* ignore */  }
        case 109: break;
        case 14: 
          {  return symbol(sym.SUB);  }
        case 110: break;
        case 45: 
          {  return symbol(sym.AND);  }
        case 111: break;
        case 46: 
          {  return symbol(sym.OR);  }
        case 112: break;
        case 48: 
          {  return symbol(sym.LE);  }
        case 113: break;
        case 49: 
          {  return symbol(sym.GE);  }
        case 114: break;
        case 51: 
          {  return symbol(sym.IF);  }
        case 115: break;
        case 54: 
          {  return symbol(sym.DO);  }
        case 116: break;
        case 64: 
          {  return symbol(sym.END);  }
        case 117: break;
        case 65: 
          {  return symbol(sym.FUN);  }
        case 118: break;
        case 70: 
          {  return symbol(sym.NOT);  }
        case 119: break;
        case 71: 
          {  return symbol(sym.INT);  }
        case 120: break;
        case 76: 
          {  return symbol(sym.VAR);  }
        case 121: break;
        case 0: 
        case 2: 
        case 5: 
        case 6: 
        case 7: 
        case 8: 
        case 9: 
        case 17: 
        case 30: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 47: 
        case 52: 
        case 53: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 66: 
        case 67: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 77: 
        case 79: 
        case 83: 
        case 84: 
        case 87: 
        case 88: 
        case 90: 
        case 92: 
          {  return symbol(sym.ID, yytext());  }
        case 122: break;
        case 97: 
          {  return symbol(sym.PRINT);  }
        case 123: break;
        case 96: 
          {  return symbol(sym.BEGIN);  }
        case 124: break;
        case 95: 
          {  return symbol(sym.WHILE);  }
        case 125: break;
        case 94: 
          {  return symbol(sym.FLOOR);  }
        case 126: break;
        case 93: 
          {  return symbol(sym.FLOAT);  }
        case 127: break;
        case 91: 
          {  return symbol(sym.CEIL);  }
        case 128: break;
        case 89: 
          {  return symbol(sym.BOOL);  }
        case 129: break;
        case 85: 
          {  return symbol(sym.SIZE);  }
        case 130: break;
        case 27: 
          {  return symbol(sym.SRPAR);  }
        case 131: break;
        case 26: 
          {  return symbol(sym.SLPAR);  }
        case 132: break;
        case 25: 
          {  return symbol(sym.CRPAR);  }
        case 133: break;
        case 24: 
          {  return symbol(sym.CLPAR);  }
        case 134: break;
        case 23: 
          {  return symbol(sym.RPAR);  }
        case 135: break;
        case 22: 
          {  return symbol(sym.LPAR);  }
        case 136: break;
        case 21: 
          {  return symbol(sym.COLON);  }
        case 137: break;
        case 18: 
          {  return symbol(sym.EQUAL);  }
        case 138: break;
        case 29: 
          {  return symbol(sym.COMMA);  }
        case 139: break;
        case 78: 
          {  return symbol(sym.THEN);  }
        case 140: break;
        case 80: 
          {  return symbol(sym.REAL);  }
        case 141: break;
        case 81: 
          {  return symbol(sym.READ);  }
        case 142: break;
        case 82: 
          {  return symbol(sym.ELSE);  }
        case 143: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbol(sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
