
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 41;
  public static final int UMINUS = 42;
  public static final int NUMBER = 43;
  public static final int SEMI = 44;
  public static final int EOF = 45;
  public static final int PLUS = 46;
  public static final int error = 47;
  public static final int RPAREN = 48;
  public static final int TIMES = 49;
  public static final int LPAREN = 50;
  
	public static final int ADD = 53;
	public static final int SUB = 1;
	public static final int MUL = 2;
	public static final int DIV = 3;
	
	public static final int AND = 4;
	public static final int OR = 5;
	public static final int NOT = 6;
	
	public static final int EQUAL = 7;
	public static final int LT = 8;
	public static final int GT = 9;
	public static final int LE = 10;
	public static final int GE = 11;
	
	public static final int ASSIGN = 12;
	
	public static final int LPAR = 13;
	public static final int RPAR = 14;
	public static final int CLPAR = 15;
	public static final int CRPAR = 16;
	public static final int SLPAR = 17;
	public static final int SRPAR = 18;
	
	public static final int COLON = 19;
	public static final int SEMICOLON = 20;
	public static final int COMMA = 21;
	
	public static final int IF = 22;
	public static final int THEN = 23;
	public static final int WHILE = 24;
	public static final int DO = 25;
	public static final int READ = 26;
	public static final int ELSE = 27;
	public static final int BEGIN = 28;
	public static final int END = 29;
	public static final int PRINT = 30;
	public static final int INT = 31;
	public static final int BOOL = 32;
	public static final int REAL = 33;
	public static final int VAR = 34;
	public static final int SIZE = 35;
	public static final int FLOAT = 36;
	public static final int FLOOR = 37;
	public static final int CEIL = 38;
	public static final int FUN = 39;
	public static final int RETURN = 40;
	public static final int KILL = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER"
  };
}

